services:
  db:
    image: postgres:17
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtgcards
    volumes:
      - mtg_postgres_data:/var/lib/postgresql/data
      - ./app/drizzle:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mtg_postgres_data:
